### ISSUE TITLE
segfault in libcxl

### ISSUE THREAD

**Issue by ibm-genwqe** [ibm-capi/libcxl#8]
The last patch 
@@ -916,7 +927,10 @@ int cxl_read_event(struct cxl_afu_h *afu, struct cxl_event *event)
    afu->event_buf_end = (struct cxl_event *)
        ((char *)afu->event_buf + size);
-   return fetch_cached_event(afu, event);
-   rc = fetch_cached_event(afu, event);
-   if (p)
-       free(p);
-   return rc;

does somehow corrupt our memory in a way that the next free after the free above results in a core dump. I was not able to find any leak in our memory but removing this "free(p)" did fix the problem.
So the free must be moved to cxl_afu_free()

**Comment by fhaverkamp** [comment]
Eberhard is this still an issue?

**Comment by ibm-genwqe** [comment]
This problem was not seen anymore.
